# Generated by Django 4.1.1 on 2022-10-24 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_post_liked_delete_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='liked',
            new_name='like',
        ),
    ]
