# Generated by Django 4.1.1 on 2022-10-27 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_rename_liked_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='network.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=140),
        ),
    ]
